import json
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Credentials
INSTAGRAM_USERNAME = os.getenv("INSTAGRAM_USERNAME")
INSTAGRAM_PASSWORD = os.getenv("INSTAGRAM_PASSWORD")
TIKTOK_USERNAME = os.getenv("TIKTOK_USERNAME")
TIKTOK_PASSWORD = os.getenv("TIKTOK_PASSWORD")
TIKTOK_ACCOUNT_NAME = os.getenv("TIKTOK_ACCOUNT_NAME", "")

# Paths
BASE_DIR = Path(__file__).parent
MEDIA_DIR = BASE_DIR / "media"
PROGRESS_FILE = BASE_DIR / "progress.json"
BROWSER_STATE_DIR = BASE_DIR / "browser_state"
USER_CONFIG_FILE = BASE_DIR / "user_config.json"

# Load user config if it exists (generated by configure.py)
_user_config = {}
if USER_CONFIG_FILE.exists():
    with open(USER_CONFIG_FILE) as f:
        _user_config = json.load(f)

# Settings (user_config.json overrides defaults)
HEADLESS = True  # Set to False for debugging
POST_INTERVAL_HOURS = _user_config.get("post_interval_hours", 4.8)
POSTS_PER_DAY = _user_config.get("posts_per_day", 5)
HUMAN_DELAY_MIN = 2
HUMAN_DELAY_MAX = 5

# Platform toggles
PLATFORMS = _user_config.get("platforms", {"youtube": True, "tiktok": False})
USE_YOUTUBE = PLATFORMS.get("youtube", True)
USE_TIKTOK = PLATFORMS.get("tiktok", False)

# TikTok account name (from env or user_config)
if not TIKTOK_ACCOUNT_NAME:
    TIKTOK_ACCOUNT_NAME = _user_config.get("tiktok_account_name", "")
